### ISSUE TITLE
Change Zooniverse footer

### ISSUE THREAD

**Issue by VVH** [zooniverse/Zooniverse#44]
At the moment the footer has a 'Space' tab, 2 'Nature' tabs and one 'Biology'. Doesn't seem quite right. Can this be changed to:

Space [with current projects]

Nature: Snapshot Sarengeti, Penguin Watch, Plankton Portal, Condor Watch

Humanities and Transcription: Old Weather, Operation War Diary, Notes from Nature, Ancient Lives

Biology and Physics: Worm Watch, Cell Slider, Higgs Hunter

Example of current footer: http://www.penguinwatch.org/

**Comment by chrissnyder** [comment]
Changed with a couple minor mods. i shortened "Humanities and Transcription" to just "Humanities" in the interest of keeping the text on one line. Also added a project or two, though Cyclone Center doesn't really fit anywhere (sadly).

**Comment by VVH** [comment]
Let's just hope that Philip Brohan doesn't object :)

**Comment by DarrenMcRoy** [comment]
Cyclone Center could go in Nature. Storms are a force of nature.

Also, do we need Cell Slider? It's fairly defunct at the moment.

**Comment by chrissnyder** [comment]
Yea, that's where I ended up putting CC. I did change the title to "Natural World". I liked the sound of it, though I'm not really sure what it encompasses.

Cell Slider is still being actively maintained and updated by CRUK. There's no community to speak of, given the lack of any sort of discussion tools, but it is still quite useful.

Closing this. Feel free to re-open if someone has strong thoughts.

**Comment by VVH** [comment]
Could we please add Ancient Lives to Humanities?

**Comment by chrissnyder** [comment]
Done.
